#          ______                                  ____  _ ____
#   __  __/ ____/___  _________ ____              / __ \(_) __ \____ _____  ___  _____
#  / / / / /_  / __ \/ ___/ __ `/ _ \   ______   / /_/ / / /_/ / __ `/ __ \/ _ \/ ___/
# / /_/ / __/ / /_/ / /  / /_/ /  __/  /_____/  / ____/ / ____/ /_/ / /_/ /  __/ /
# \__,_/_/    \____/_/   \__, /\___/           /_/   /_/_/    \__,_/ .___/\___/_/
#                       /____/                                    /_/

# UFORGE © 2021

# PiPaper
# A simple paper money plugin

