# PiPaper v1.2
# uForge © 2021
# A simple paper interact plugin.
# Wiki: https://github.com/uForge-NET/pipaper/wiki

settings:
  interactType: right

papers:
  example-paper:
    displayName: "&eExample Paper"
    removeAfterUse: true
    lores:
      - '&bRight click to air with me!'
      - '&euForge!'
    commands:
      - eco give {player} 1000
  healer:
    displayName: "&cHeal!"
    removeAfterUse: false
    lores:
      - '&eHeal yourself!'
    commands:
      - heal {player}
